### ISSUE TITLE
Having to save the calendar again every day is weird.

### ISSUE THREAD

**Issue by johntyree** [andrayantelo/calendar-reboot#55]
My intuition about saving was more like "create calendar" than "save".

I expected the check marks I was making to be saved automatically. When I refreshed they were all gone. I can't think of a case right now where I'd want that.

**Comment by andrayantelo** [comment]
So every time you place a checkmark
you want the calendar to save? what if you check an entire week, then you're like nah, i don't want those i'll leave it as is, close the browser, reopen later, but because of automatically saving checkmarks after they are placed, they are still there.

**Comment by johntyree** [comment]
Under what scenario would you check the entire week and then decide "Nah... I didn't actually do that and let's pretend that never happened" and then *not* expect to uncheck it?

Also, think about the most common use case and make that easy. Is it more likely that someone will come add a check, or come and add a bunch of checks and then not uncheck them but also not want them anymore?

**Comment by andrayantelo** [comment]
Done.

**Comment by andrayantelo** [comment]
Maybe someday add a thing somewhere that says "progress saved" ?

**Comment by johntyree** [comment]
Doesn't save until you create a checkmark. I expected it to save when I made the calendar.

Also the save button is still present, what does that do now?

**Comment by andrayantelo** [comment]
Calendar saves when calendar is created and when checkmarks are added or removed, when a calendar is displayed after clicking it's name from the dropdown. The function displayCalendar will also save it after displaying it. displayCalendar is used when a calendar is selected from the dropdown, and also when the page loads and a calendar is loaded from localStorage.
